## Tensors and Math

In [124]:
import tensorflow as tf
import numpy as np

In [125]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [126]:
tensor_one_d = tf.constant([2, 0, -8, 7, -6],dtype=tf.float64)
casted_tensor_one_d_type_int = tf.cast(tensor_one_d, dtype=tf.int16)
casted_tensor_one_d_type_bool = tf.cast(tensor_one_d, dtype=tf.bool)

print(tensor_one_d)
print(casted_tensor_one_d_type_int)
print(casted_tensor_one_d_type_bool)

tf.Tensor([ 2.  0. -8.  7. -6.], shape=(5,), dtype=float64)
tf.Tensor([ 2  0 -8  7 -6], shape=(5,), dtype=int16)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [127]:
tensor_bool = tf.constant([True, False, False, True])
print(tensor_bool)

tf.Tensor([ True False False  True], shape=(4,), dtype=bool)


In [128]:
tensor_string = tf.constant(["Hello", "World"])
print(tensor_string)

tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)


In [129]:
tensor_two_d = tf.constant([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [-9,-2, 9]
                           ])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-9 -2  9]], shape=(4, 3), dtype=int32)


In [130]:
tensor_three_d = tf.constant([[[1,2,3],
                              [5,6,7]],
                             [[8,9,10],
                              [4,7,-2]],
                             [[7,3,-5],
                              [1,5,0]],
                             [[-1,-3,-30],
                              [2,5,-29]]])
print(tensor_three_d)

tf.Tensor(
[[[  1   2   3]
  [  5   6   7]]

 [[  8   9  10]
  [  4   7  -2]]

 [[  7   3  -5]
  [  1   5   0]]

 [[ -1  -3 -30]
  [  2   5 -29]]], shape=(4, 2, 3), dtype=int32)


In [131]:
print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)

()
(5,)
(4, 3)
(4, 2, 3)


In [132]:
print(tensor_zero_d.ndim)
print(tensor_one_d.ndim)
print(tensor_two_d.ndim)
print(tensor_three_d.ndim)

0
1
2
3


In [133]:
tensor_four_d = tf.constant([[[[1,2,3],
                              [5,6,7]],
                             [[8,9,10],
                              [4,7,-2]],
                             [[7,3,-5],
                              [1,5,0]],
                             [[-1,-3,-30],
                              [2,5,-29]]],
                             [[[8,7,3],
                              [5,6,-4]],
                             [[89,29,-10],
                              [42,17,-2]],
                             [[72,31,-15],
                              [1,54,10]],
                             [[-13,-53,-30],
                              [24,56,-29]]],
                             [[[11,32,3],
                              [25,-36,-79]],
                             [[82,94,10],
                              [47,76,-62]],
                             [[79,73,-75],
                              [-91,59,80]],
                             [[-18,-33,-30],
                              [22,51,-29]]]])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   3]
   [  5   6   7]]

  [[  8   9  10]
   [  4   7  -2]]

  [[  7   3  -5]
   [  1   5   0]]

  [[ -1  -3 -30]
   [  2   5 -29]]]


 [[[  8   7   3]
   [  5   6  -4]]

  [[ 89  29 -10]
   [ 42  17  -2]]

  [[ 72  31 -15]
   [  1  54  10]]

  [[-13 -53 -30]
   [ 24  56 -29]]]


 [[[ 11  32   3]
   [ 25 -36 -79]]

  [[ 82  94  10]
   [ 47  76 -62]]

  [[ 79  73 -75]
   [-91  59  80]]

  [[-18 -33 -30]
   [ 22  51 -29]]]], shape=(3, 4, 2, 3), dtype=int32)


In [134]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [135]:
converted_tensor_from_np = tf.convert_to_tensor(np_array)
print(converted_tensor_from_np)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [136]:
eye_tensor = tf.eye(num_rows=5, num_columns=5, batch_shape=[3,2], dtype=tf.dtypes.float16)
print(4*eye_tensor)

tf.Tensor(
[[[[4. 0. 0. 0. 0.]
   [0. 4. 0. 0. 0.]
   [0. 0. 4. 0. 0.]
   [0. 0. 0. 4. 0.]
   [0. 0. 0. 0. 4.]]

  [[4. 0. 0. 0. 0.]
   [0. 4. 0. 0. 0.]
   [0. 0. 4. 0. 0.]
   [0. 0. 0. 4. 0.]
   [0. 0. 0. 0. 4.]]]


 [[[4. 0. 0. 0. 0.]
   [0. 4. 0. 0. 0.]
   [0. 0. 4. 0. 0.]
   [0. 0. 0. 4. 0.]
   [0. 0. 0. 0. 4.]]

  [[4. 0. 0. 0. 0.]
   [0. 4. 0. 0. 0.]
   [0. 0. 4. 0. 0.]
   [0. 0. 0. 4. 0.]
   [0. 0. 0. 0. 4.]]]


 [[[4. 0. 0. 0. 0.]
   [0. 4. 0. 0. 0.]
   [0. 0. 4. 0. 0.]
   [0. 0. 0. 4. 0.]
   [0. 0. 0. 0. 4.]]

  [[4. 0. 0. 0. 0.]
   [0. 4. 0. 0. 0.]
   [0. 0. 4. 0. 0.]
   [0. 0. 0. 4. 0.]
   [0. 0. 0. 0. 4.]]]], shape=(3, 2, 5, 5), dtype=float16)


In [137]:
fill_tensor = tf.fill(dims=[4,2,3], value=42)
print(fill_tensor)

tf.Tensor(
[[[42 42 42]
  [42 42 42]]

 [[42 42 42]
  [42 42 42]]

 [[42 42 42]
  [42 42 42]]

 [[42 42 42]
  [42 42 42]]], shape=(4, 2, 3), dtype=int32)


In [138]:
ones_tensor = tf.ones(shape=[5,3], dtype=tf.float16)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float16)


In [139]:
ones_like_tensor = tf.ones_like(tensor_three_d)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]], shape=(4, 2, 3), dtype=int32)


In [140]:
zeroes_like_tensor = tf.zeros_like(tensor_three_d)
print(zeroes_like_tensor)

tf.Tensor(
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]], shape=(4, 2, 3), dtype=int32)


In [141]:
shape_tensor = tf.shape(tensor_three_d)
print(shape_tensor)

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [142]:
rank_tensor = tf.rank(tensor_three_d)
print(rank_tensor)

tf.Tensor(3, shape=(), dtype=int32)


In [143]:
size_tensor = tf.size(tensor_four_d, out_type=tf.float64)
print(size_tensor)

tf.Tensor(72.0, shape=(), dtype=float64)


In [144]:
random_tensor = tf.random.normal(shape=[5,3],mean=50,stddev=3, dtype=tf.float16)
print(random_tensor)

tf.Tensor(
[[48.88 47.47 51.56]
 [52.34 44.7  48.44]
 [51.22 53.22 51.  ]
 [52.06 51.12 49.56]
 [48.03 50.9  50.84]], shape=(5, 3), dtype=float16)


In [145]:
random_tensor_uniform = tf.random.uniform(shape=[5,3],minval=5,maxval=25, dtype=tf.float16)
print(random_tensor_uniform)

tf.Tensor(
[[24.53  13.984 11.29 ]
 [14.2   17.06   7.5  ]
 [15.84  20.69   9.31 ]
 [19.31   5.234  6.992]
 [21.28  20.8   22.   ]], shape=(5, 3), dtype=float16)


In [146]:
tensor_indexed = tf.constant([0,1,2,3,4,5,6,7,8,9])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:6])
print(tensor_indexed[:-1])
print(tensor_indexed[0:])
print(tensor_indexed[::2])
print(tensor_indexed[0:-1:3])


tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([0 3 6], shape=(3,), dtype=int32)


In [147]:
print(tensor_two_d[2, :])
print(tensor_two_d[0:3, 0:2])
print(tensor_two_d[..., 1])

tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)
tf.Tensor([ 2  5  8 -2], shape=(4,), dtype=int32)


In [148]:
print(tensor_three_d)
print(tensor_three_d[1, 1:, 0:-1])
print(tensor_three_d[0:-1, 1:, :])

tf.Tensor(
[[[  1   2   3]
  [  5   6   7]]

 [[  8   9  10]
  [  4   7  -2]]

 [[  7   3  -5]
  [  1   5   0]]

 [[ -1  -3 -30]
  [  2   5 -29]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor([[4 7]], shape=(1, 2), dtype=int32)
tf.Tensor(
[[[ 5  6  7]]

 [[ 4  7 -2]]

 [[ 1  5  0]]], shape=(3, 1, 3), dtype=int32)


In [149]:
tf.abs(tf.constant([[-1, -89, -63, -99],
                    [-3, -43, -45, -69]]))

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1, 89, 63, 99],
       [ 3, 43, 45, 69]], dtype=int32)>

In [150]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [151]:
x = tf.sqrt(tf.constant((-2.25)**2 + (4.75)**2))
print(x)

tf.Tensor(5.255949, shape=(), dtype=float32)


In [152]:
x = [1, 2, 3, 4, 5]
y = 1
tf.add(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [153]:
x_1 = tf.constant([1, 2, 3, 6, -9, 20])
x_2 = tf.constant([4, 5, 6, 7 , 6 , -76])
print(tf.add(x_1, x_2))

x_1 = tf.constant([1, 2, 3, 6, -9, 20])
x_2 = tf.constant([4, 5, 6, 7 , 6 , -76])
print(tf.multiply(x_1, x_2))

x_1 = tf.constant([1, 2, 3, 6, -9, 20])
x_2 = tf.constant([4, 5, 6, 7 , 6 , -76])
print(tf.subtract(x_1, x_2))

x_1 = tf.constant([1, 2, 3, 6, -9, 20])
x_2 = tf.constant([4, 5, 6, 7 , 6 , -76])
print(tf.divide(x_1, x_2))

tf.Tensor([  5   7   9  13  -3 -56], shape=(6,), dtype=int32)
tf.Tensor([    4    10    18    42   -54 -1520], shape=(6,), dtype=int32)
tf.Tensor([ -3  -3  -3  -1 -15  96], shape=(6,), dtype=int32)
tf.Tensor([ 0.25        0.4         0.5         0.85714286 -1.5        -0.26315789], shape=(6,), dtype=float64)


In [154]:
print(tf.constant(3.0) / 0.0)

print(tf.math.divide_no_nan(3.0, 0.0))

x_1 = tf.constant([1, 2, 3, 6, -9, 20], dtype=tf.float32)
x_2 = tf.constant([4, 5, 6, 7 , 6 , -76], dtype=tf.float32)
print(tf.math.divide_no_nan(x_1, x_2))


tf.Tensor(inf, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor([ 0.25        0.4         0.5         0.85714287 -1.5        -0.2631579 ], shape=(6,), dtype=float32)


In [155]:
x_1 = tf.constant([1, 2, 3, 6, -9, 20], dtype=tf.float32)
x_2 = tf.constant([[4], [5], [6]], dtype=tf.float32)
print(tf.math.multiply(x_1, x_2))

tf.Tensor(
[[  4.   8.  12.  24. -36.  80.]
 [  5.  10.  15.  30. -45. 100.]
 [  6.  12.  18.  36. -54. 120.]], shape=(3, 6), dtype=float32)


In [156]:
x_1 = tf.constant([1, 2, 3, 6, -9, 20], dtype=tf.float32)
x_2 = tf.constant([4, 5, 6, 7 , 6 , -76], dtype=tf.float32)

tf.minimum(x_1, x_2)

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([  1.,   2.,   3.,   6.,  -9., -76.], dtype=float32)>

In [157]:
A = tf.constant([2, 10, 30, 35, 6])
tf.math.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [158]:
B = tf.constant([[2, 20, 30, 3, 35],
                 [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
tf.math.argmax(B, 1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([4, 2, 1])>

In [159]:
B = tf.constant([[2, 20, 30, 3, 35],
                 [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
tf.math.argmax(B, 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 0])>

In [160]:
x = tf.constant([2, 4])
y = tf.constant(2)
tf.math.equal(x, y)


<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [161]:
x = tf.constant([2, 4])
y = tf.constant([2, 4])
tf.math.equal(x, y)


<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [162]:
x_1 = tf.constant([1, 2, 3, 6, -9, 20], dtype=tf.int64)
x_2 = tf.constant([4, 4, 6, 7 , 6 , 76], dtype=tf.int64)
tf.pow(x_1, x_2)

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([     1,     16,    729, 279936, 531441,      0])>

In [163]:
# x has a shape of (2, 3) (two rows and three columns):
x = tf.constant([[1, 1, 1], [1, 1, 1]])
x.numpy()

# sum all the elements
# 1 + 1 + 1 + 1 + 1+ 1 = 6
tf.reduce_sum(x).numpy()

6

In [164]:
# reduce along the first dimension
# the result is [1, 1, 1] + [1, 1, 1] = [2, 2, 2]
tf.reduce_sum(x, 0).numpy()

array([2, 2, 2], dtype=int32)

In [165]:
print(tensor_three_d)

print(tf.reduce_sum(tensor_three_d,0).numpy())
print(tf.reduce_mean(tensor_three_d,0).numpy())
print(tf.reduce_min(tensor_three_d,0).numpy())
print(tf.reduce_max(tensor_three_d,0).numpy())

tf.Tensor(
[[[  1   2   3]
  [  5   6   7]]

 [[  8   9  10]
  [  4   7  -2]]

 [[  7   3  -5]
  [  1   5   0]]

 [[ -1  -3 -30]
  [  2   5 -29]]], shape=(4, 2, 3), dtype=int32)
[[ 15  11 -22]
 [ 12  23 -24]]
[[ 3  2 -5]
 [ 3  5 -6]]
[[ -1  -3 -30]
 [  1   5 -29]]
[[ 8  9 10]
 [ 5  7  7]]


In [166]:
print(tensor_two_d)
tf.math.top_k(tensor_two_d,k=2)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-9 -2  9]], shape=(4, 3), dtype=int32)


TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  2],
       [ 6,  5],
       [ 9,  8],
       [ 9, -2]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [167]:
x_1 = tf.constant([[1, 2, 3],
                  [6, -9, 20],
                   [-20, 9, 7]])
x_2 = tf.constant([[4, 5, 6, 9],
                   [7, 6 , -76, -5],
                   [5, -6, -23, -6]])
print(x_1.shape)
print(x_2.shape)
tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

(3, 3)
(3, 4)


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[  33,   -1, -215,  -19],
       [  61, -144,  260,  -21],
       [  18,  -88, -965, -267]], dtype=int32)>

In [168]:
print(x_1@x_2)
print(np.dot(x_1,x_2))

tf.Tensor(
[[  33   -1 -215  -19]
 [  61 -144  260  -21]
 [  18  -88 -965 -267]], shape=(3, 4), dtype=int32)
[[  33   -1 -215  -19]
 [  61 -144  260  -21]
 [  18  -88 -965 -267]]


In [169]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  1,   6, -20],
       [  2,  -9,   9],
       [  3,  20,   7]], dtype=int32)>

In [170]:
tf.transpose(x_2)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[  4,   7,   5],
       [  5,   6,  -6],
       [  6, -76, -23],
       [  9,  -5,  -6]], dtype=int32)>

In [171]:
three_d_x_1 = tf.constant([[[1, 2],
                            [6, 0]],
                           [[0, 6],
                            [0, -4]],
                           [[10, -2],
                            [23, 0]]])

three_d_x_2 = tf.constant([[[11, 12, 3],
                            [16, -19, 2]],
                           [[1, 26, 14],
                            [3, -14, -13]],
                           [[1, -22, -3],
                            [3, -4, 3]]])

print(three_d_x_1)
print(three_d_x_2)

print(tf.linalg.matmul(three_d_x_1,three_d_x_2))

tf.Tensor(
[[[ 1  2]
  [ 6  0]]

 [[ 0  6]
  [ 0 -4]]

 [[10 -2]
  [23  0]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[ 11  12   3]
  [ 16 -19   2]]

 [[  1  26  14]
  [  3 -14 -13]]

 [[  1 -22  -3]
  [  3  -4   3]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[  43  -26    7]
  [  66   72   18]]

 [[  18  -84  -78]
  [ -12   56   52]]

 [[   4 -212  -36]
  [  23 -506  -69]]], shape=(3, 2, 3), dtype=int32)


In [172]:
three_by_three_x_1 = tf.constant([[1, 2, 3],
                                  [6, -9, 20],
                                  [-20, 9, 7]], dtype=tf.float32)
tf.linalg.inv(three_by_three_x_1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.1614618 , -0.00863787, -0.04451827],
       [ 0.2936877 , -0.04451827,  0.0013289 ],
       [ 0.08372093,  0.03255814,  0.01395349]], dtype=float32)>

In [173]:
s,u,v = tf.linalg.svd(three_by_three_x_1)
print(s)
print(u)
print(v)

tf.Tensor([24.195642  21.616907   2.8774347], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.03249778  0.10551988  0.993886  ]
 [ 0.6776755   0.7285965  -0.09951282]
 [-0.73464257  0.6767661  -0.04783047]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.7766439  -0.41903418  0.47035572]
 [-0.5226505  -0.01181625  0.8524651 ]
 [ 0.35165417  0.9078935   0.22818552]], shape=(3, 3), dtype=float32)


In [174]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])

B = np.array([[2,9,0,3,0],
              [3,6,8,-2,2],
              [1,3,5,0,1],
              [3,0,2,0,5]])

print(A.shape)
print(B.shape)

print("Matmul C =: \n")
print(np.matmul(A,B), "\n")

print("Einsum C=: \n")
print(np.einsum("ij,jk->ik",A,B))

(3, 4)
(4, 5)
Matmul C =: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 

Einsum C=: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [175]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])

B = np.array([[2,9,0,3],
              [3,6,8,-2],
              [1,3,5,0]])

print(A.shape)
print(B.shape)

print("Hardamond C =: \n")
print(A*B, "\n")

print("Einsum C=: \n")
print(np.einsum("ij,ij->ij",A,B))

(3, 4)
(3, 4)
Hardamond C =: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]] 

Einsum C=: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [176]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])

print("Transposed A = :\n")
print(A.T)

print("Einsum Transpose A = :\n")
print(np.einsum("ij->ji",A))

Transposed A = :

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]
Einsum Transpose A = :

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [177]:
# Create a 2x3x4 array of random numbers between -5 and 15
array1 = np.random.randint(-5, 15, size=(2, 3, 4))

# Create a 2x4x5 array of random numbers between -5 and 15
array2 = np.random.randint(-5, 15, size=(2, 4, 5))

print("Array 1 =: \n")
print(array1, "\n")

print("Array 2 =: \n")
print(array2, "\n")

print("Batch Multiplication C =: \n")
print(np.matmul(array1, array2), "\n")

print("Einsum C=: \n")
print(np.einsum("bij,bjk -> bik",array1,array2))


Array 1 =: 

[[[ 6  1  6  3]
  [-5 12  8  8]
  [-1  0 -3  8]]

 [[ 7  7  0  9]
  [ 6 -5  7  0]
  [-4 -1  6  6]]] 

Array 2 =: 

[[[ 5 10  8 14  4]
  [-1  2 11  5  7]
  [ 7  3 -3  8 10]
  [ 4  1  0  8 -5]]

 [[-2  8  3  2  2]
  [ 4  0  2 10 -2]
  [-3  1  1  5 14]
  [14  6  4 -2  5]]] 

Batch Multiplication C =: 

[[[ 83  83  41 161  76]
  [ 51   6  68 118 104]
  [  6 -11   1  26 -74]]

 [[140 110  71  66  45]
  [-53  55  15  -3 120]
  [ 70  10  16   0 108]]] 

Einsum C=: 

[[[ 83  83  41 161  76]
  [ 51   6  68 118 104]
  [  6 -11   1  26 -74]]

 [[140 110  71  66  45]
  [-53  55  15  -3 120]
  [ 70  10  16   0 108]]]


In [178]:
# Create a 2x3x4 array of random numbers between -5 and 15
array1 = np.random.randint(-5, 15, size=(2, 3, 4))

print("Sum of Array 1 =: \n")
print(np.sum(array1), "\n")

print("Einsum Sum of Array 1 =: \n")
print(np.einsum("bij->",array1))

Sum of Array 1 =: 

101 

Einsum Sum of Array 1 =: 

101


In [179]:
array1 = np.random.randint(-5, 15, size=(3, 4))

print("Array 1 =: \n")
print(array1, "\n")

print("Axis 0 Sum A =: \n")
print(np.sum(array1, axis=0), "\n")

print("Einsum Axis 1 Sum A =: \n")
print(np.einsum("ij->j",array1))

print("Axis 1 Sum A =: \n")
print(np.sum(array1, axis=1), "\n")

print("Einsum Axis 0 Sum A =: \n")
print(np.einsum("ij->i",array1), "\n")


Array 1 =: 

[[ 9  2  4  2]
 [ 2  6 13  2]
 [ 8 11  8  4]] 

Axis 0 Sum A =: 

[19 19 25  8] 

Einsum Axis 1 Sum A =: 

[19 19 25  8]
Axis 1 Sum A =: 

[17 23 31] 

Einsum Axis 0 Sum A =: 

[17 23 31] 





## Common Tensorflow Functions



In [180]:
print(tensor_three_d)
print(tf.expand_dims(tensor_three_d, axis=0))

tf.Tensor(
[[[  1   2   3]
  [  5   6   7]]

 [[  8   9  10]
  [  4   7  -2]]

 [[  7   3  -5]
  [  1   5   0]]

 [[ -1  -3 -30]
  [  2   5 -29]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[[  1   2   3]
   [  5   6   7]]

  [[  8   9  10]
   [  4   7  -2]]

  [[  7   3  -5]
   [  1   5   0]]

  [[ -1  -3 -30]
   [  2   5 -29]]]], shape=(1, 4, 2, 3), dtype=int32)


In [181]:
x = tf.constant([2,3,4,5])
print(x.shape)
print(tf.expand_dims(x, axis=0))
print(tf.expand_dims(x, axis=1))

(4,)
tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[2]
 [3]
 [4]
 [5]], shape=(4, 1), dtype=int32)


In [182]:
x_squeezed = tf.constant([[[1,2,3],
                       [4,5,6]]])
print(x_squeezed)
print(tf.squeeze(x_squeezed, axis=0))

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [183]:
print(tensor_two_d)
print(tf.reshape(tensor_two_d, [2, 3, 2]))
print(tf.reshape(tensor_two_d, [6,2]))
print(tf.reshape(tensor_two_d, [1, -1]))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-9 -2  9]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 -9]
  [-2  9]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 -9]
 [-2  9]], shape=(6, 2), dtype=int32)
tf.Tensor([[ 1  2  3  4  5  6  7  8  9 -9 -2  9]], shape=(1, 12), dtype=int32)


In [184]:
t1 = [[1, 2, 3],
      [4, 5, 6]]

t2 = [[7, 8, 9],
      [10, 11, 12]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

print(tf.concat([t1, t2], 0))
print(tf.concat([t1, t2], 1))

(2, 3)
(2, 3)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [185]:
tf.stack([t1, t2], axis = 0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [186]:
tf.stack([t1, t2], axis = 2)

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]], dtype=int32)>

In [187]:
tf.stack([t1, t2, t1], axis = 0)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]], dtype=int32)>

In [188]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[1, 1,],
                        [2, 2]])
# 'constant_values' is 0.
# rank of 't' is 2.
print(tf.pad(t, paddings, "CONSTANT"))

print(tf.pad(t, paddings, "REFLECT"))

print(tf.pad(t, paddings, "SYMMETRIC"))

tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]], shape=(4, 7), dtype=int32)


In [189]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params[1:4].numpy())

print(tf.gather(params, tf.range(1,4).numpy()))

print(tf.gather(params, [0, 3, 5]).numpy())

[b'p1' b'p2' b'p3']
tf.Tensor([b'p1' b'p2' b'p3'], shape=(3,), dtype=string)
[b'p0' b'p3' b'p5']


In [190]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(params.shape)
print(tf.gather(params, indices=[3,1]).numpy())

print(tf.gather(params, indices=[2,1], axis=1).numpy())

(4, 3)
[[30. 31. 32.]
 [10. 11. 12.]]
[[ 2.  1.]
 [12. 11.]
 [22. 21.]
 [32. 31.]]


In [191]:
tf.gather_nd(
    indices=[[0, 0],
             [1, 1]],
    params = [['a', 'b'],
              ['c', 'd']]).numpy()


array([b'a', b'd'], dtype=object)

In [192]:
tf.gather_nd(
    indices = [[1],
               [0]],
    params = [['a', 'b', 'c'],
              ['d', 'e', 'f']]).numpy()

array([[b'd', b'e', b'f'],
       [b'a', b'b', b'c']], dtype=object)

In [193]:
tf.gather_nd(
    indices = [[0, 1],
               [1, 0],
               [2, 4],
               [3, 2],
               [4, 1]],
    params=tf.zeros([5, 7, 3])).shape.as_list()


[5, 3]

## Ragged Tensors

In [198]:
modi_tensor_two_d = [[1,2,0],
                     [3,],
                     [1,5,6,5,6],
                     [2,3]]

tensor_ragged = tf.ragged.constant(modi_tensor_two_d)
print(tensor_ragged)
print(tensor_ragged.shape)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>
(4, None)


In [200]:
# Aliases for True & False so data and mask line up.
T, F = (True, False)

In [201]:
tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[T, F, T], [F, F, F], [T, F, F]]).to_list()

[[1, 3], [], [7]]

In [202]:
tf.ragged.boolean_mask(  # Mask a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([[F, F, T], [F], [T, T]])).to_list()


[[3], [], [5, 6]]

In [203]:
tf.ragged.boolean_mask(  # Mask rows of a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([True, False, True])).to_list()


[[1, 2, 3], [5, 6]]

In [205]:
print(tf.RaggedTensor.from_row_splits(
      values=[3, 1, 4, 1, 5, 9, 2, 6],
      row_splits=[0, 2, 5, 7, 8, 8]))


<tf.RaggedTensor [[3, 1], [4, 1, 5], [9, 2], [6], []]>


In [206]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [207]:
print(tf.RaggedTensor.from_row_limits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_limits=[4, 4, 7, 8, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [208]:
dt = tf.constant([[5, 7, 0],
                  [0, 3, 0],
                  [6, 0, 0]])
tf.RaggedTensor.from_tensor(dt)

tf.RaggedTensor.from_tensor(dt, lengths=[1, 0, 3])


<tf.RaggedTensor [[5], [], [6, 0, 0]]>

In [209]:
dt = tf.constant([[[5, 0], [7, 0], [0, 0]],
                  [[0, 0], [3, 0], [0, 0]],
                  [[6, 0], [0, 0], [0, 0]]])
tf.RaggedTensor.from_tensor(dt, lengths=([2, 0, 3], [1, 1, 2, 0, 1]))


<tf.RaggedTensor [[[5], [7]], [], [[6, 0], [], [0]]]>

## Sparse Tensors

In [210]:
tensor_sparse = tf.sparse.SparseTensor(indices=[[1, 1], [3, 4]], values=[11, 56], dense_shape=[5, 6])
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [211]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

## String Tensors

In [212]:
tensor_string = tf.constant(["hello", "i am", "a", "string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a' b'string'], shape=(4,), dtype=string)


In [213]:
tf.strings.join(tensor_string, separator=" ")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello i am a string'>

## Variables

In [217]:
x = tf.constant([1,2,3,4,5])
x_var = tf.Variable(x, name = 'var1')
print(x_var)

<tf.Variable 'var1:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>


In [225]:
#will keep on assign new value to the original array
x_var.assign_sub([3,4,12,3,7])
print(x_var)

<tf.Variable 'var1:0' shape=(5,) dtype=int32, numpy=array([-20, -26, -74, -20, -44], dtype=int32)>


In [230]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.3)

print(x_var.device)

/job:localhost/replica:0/task:0/device:CPU:0
